=== spring/spring/Documentation/Lobby/Protocol/ProtocolDescription.dtd
<!--
  This DTD describes format of Spring lobby protocol description document.


  *** notes on document structure ***

  'Source' field indicates the direction of the command, that is if
  source is 'client', the command is sent by the client, and likewise for
  the 'server'.

  'Argument' may contain some text describing the argument itself, 'Optional' tells
  us whether this argument is optional or mandatory, and 'Sentence' tells us
  if this argument may contain more than one word combined with space character
  as a delimiter.
  
  Use 'clink' element in order to reference to other commands.
  
  'Examples' may contain some text to denote actual usage of the command.

  'CommonText' entity is used for general text formatting that may contain
  some html-like tags and links to other command IDs.

-->
<!ENTITY % CommonText "(#PCDATA|clink|u|i|b|br|br2|p|ul|li|url)*">
<!ATTLIST Name
	xml:space (default | preserve) "preserve">
<!ELEMENT u %CommonText;> <!-- underline tag -->
<!ELEMENT i %CommonText;> <!-- italics tag -->
<!ELEMENT b %CommonText;> <!-- bold tag -->
<!ELEMENT br %CommonText;> <!-- same as HTML BR tag -->
<!ELEMENT br2 %CommonText;> <!-- same as 'br' but it outputs it twice -->
<!ELEMENT p %CommonText;> <!-- same as HTML P tag -->
<!ELEMENT ul (li)+> <!-- same as HTML UL tag -->
<!ELEMENT li %CommonText;> <!-- same as HTML LI tag -->
<!ELEMENT url (#PCDATA)> <!-- gets translated to "a href" html tag -->
<!-- clink is a "command link", it points to another command: -->
<!ELEMENT clink EMPTY>
<!ATTLIST clink
  name IDREF #REQUIRED
  >

<!-- root element: -->
<!ELEMENT ProtocolDescription (Intro, CommandList)>
<!ELEMENT Intro %CommonText;>
<!ELEMENT CommandList (Command*)>
<!ELEMENT Command (Arguments?, Description, Response?, Examples?)>
<!ATTLIST Command
   Name ID #REQUIRED
   Source (client|server) #REQUIRED
   >
<!ELEMENT Arguments (Argument*)>
<!ELEMENT Argument %CommonText;>
<!ATTLIST Argument
   Name NMTOKENS #REQUIRED
   Optional (yes|no) #REQUIRED
   Sentence (yes|no) #REQUIRED
   >
<!ELEMENT Description %CommonText;>
<!ELEMENT Response %CommonText;>
<!ELEMENT Examples (Example*)>
<!ELEMENT Example (#PCDATA)>

=== spring/spring/Documentation/Lobby/Protocol/ProtocolDescription.xml
<?xml version='1.0'?>
<!DOCTYPE ProtocolDescription SYSTEM "ProtocolDescription.dtd">

<!-- transform this xml into html (so you can view it in a browser): -->
<?xml-stylesheet type="text/xsl" href="xml2html.xsl"?>

<ProtocolDescription>

  <Intro>
  
  <p>
  This is a simple text protocol in a "human readable form". I decided for text protocol since
  it's easier to debug and implement on the client side. It does require some more overhead,
  but since server and clients do not communicate much anyway, this is not an issue. What
  really eats the bandwidth is the game itself, not lobby.
  </p>
  <p>
  Single word arguments are separated by spaces, "sentences" (a sentence is a series of words
  separated by spaces, denoting a single argument) are separated by TABs. Don't forget
  to replace any TABs in your sentences with spaces! If you don't, your command is invalid
  and will not be read correctly by server.
  </p>
  <p>
  A client must maintain a constant connection with server, that is if no data is to be
  transfered, client must send a PING command to the server on regular intervals. This
  ensures server to properly detect any network timeouts/disconnects. Server will automatically
  disconnect a client if no data has been received from it within a certain time period.
  Client should send some data at least on half of that interval.
  </p>
  <p>
  Whether battle is in progress or not, clients may find out by monitoring battle's founder
  status. If his status changes to "in game", battle's status is also "in game".
  </p>
  <p>
  Client's status and battle status are assumed to be 0 if not said otherwise. Each client
  should assume that every other client's status and battle status are 0 if not stated
  otherwise by the server. So when client joins the server, he is notified about statuses
  of only those users, who have status or battle status different from 0. This way we also
  save some bandwidth (although that is not really an issue here. If we were worried about
  this protocol taking up too much bandwidth, we wouldn't use text protocol, now would we?).
  </p>
  <p>
  I use two terms for "clients": a client and an user. At first user was considered to
  be a registered client, that is client who is logged-in. I started to mix the two
  terms after a while but that should not confuse you.
  </p>
  <p>
  Most of the commands that notify about some changes are forwarded to the source of the
  change too. For example: When client sends MYBATTLESTATUS command, server sends
  CLIENTBATTLESTATUS command to all users in the battle, including the client who sent
  MYBATTLESTATUS command. This is a good practice, because this way client can synchronize his
  local status with server's after server has actually updated his status (serves also as
  confirmation).
  </p>
  <p>
  All commands except for some admin specific commands are listed here. See "AdminCommands.txt"
  for those. For more details on specific command, see tryToExecCommand() method in TASServer.java.
  </p>
  <p>
  Also, check notes (under "--- NOTES ---" field) in TASServer.java since they contain some
  information and tricks on implementing this protocol.
  </p>
  <p>
  As of version 0.33, command syntax has been slightly changed. Messages may now contain IDs:
  Any message may be prefixed with a message ID. For an example:
  "#123 SAY main hello!" <br /> 
  Server will use this ID with a reply (if any reply to the message is prescribed and the command
  actually supports it - not every command type uses an ID), for an example:
  "#123 SAID main Betalord hello!" <br /> 
  The message ID has only one function: to ease tracking server responses for the client.
  Using message IDs means that client can also use synchronous communication (with certain commands),
  which makes it easier to implement certain command that require multiple responses in both directions.
  </p>
  <p>
  Legend:
  <ul>
    <li>{} = sentence = several words (at least one!) separated by space characters</li>
    <li>{} {} ... = two or more sentences. They are separated by TAB characters.</li>
    <li>words are always separated by space characters.</li>
    <li>| = separates choices ("OR")</li>
  </ul>
  </p>
  
  </Intro>

  <CommandList>

    <Command Name="PING" Source="client">
      <Arguments>
        <Argument Name="key" Optional="yes" Sentence="no">
        If used, server will respond with a "PONG key" command instead of just "PONG"
        so that the client will be able to calculate lag between server and himself.
        </Argument>
      </Arguments>
      <Description>
      Client should send this command on every few seconds to maintain constant connection to the server.
      Server will assume timeout occured if it does not hear from client for more than x seconds.
      </Description>
      <Response>
      See <clink name="PONG"/>.
      </Response>
      <Examples>
        <Example>PONG</Example>
        <Example>PONG 123</Example>
      </Examples>
    </Command>

    <Command Name="PONG" Source="server">
      <Arguments>
        <Argument Name="key" Optional="yes" Sentence="no">
        Only used if <clink name="PING"/> was using key parameter as well.
        </Argument>
      </Arguments>
      <Description>
      Used as a response to a <clink name="PING"/> command.
      </Description>
      <Response />
      <Examples>
        <Example>PING</Example>
        <Example>PING 123</Example>
      </Examples>
    </Command>

    <Command Name="TASSERVER" Source="server">
      <Arguments>
        <Argument Name="version" Optional="no" Sentence="no">
        This is server's version number (client should check if it supports this server
        version before attempting to log in. If it does not support it, it should send
        <clink name="REQUESTUPDATEFILE"/> command).
        </Argument>
        <Argument Name="udpport" Optional="no" Sentence="no">
        This is server's UDP port where "NAT Help Server" is running. This is the port to
        which clients should send their UDP packets when trying to figure out their public
        UDP source port. This is used with some NAT traversal techniques (e.g. "hole punching").
        </Argument>
      </Arguments>
      <Description>
      This is the first message (i.e. "greeting message") that client receives upon connecting to the server.
      </Description>
      <Response />
      <Examples>
        <Example>TASSERVER 0.30 8201</Example>
      </Examples>
    </Command>

    <Command Name="REQUESTUPDATEFILE" Source="client">
      <Arguments>
        <Argument Name="version" Optional="no" Sentence="no">
        Version of client's lobby program. Server will use it to verify if any update
        exists for this program version.
        </Argument>
      </Arguments>
      <Description>
      Sent by client who is trying to find out if update exist for him since he doesn't
      support this server's version (see <clink name="TASSERVER"/> command). Send it only when server version
      is NOT supported by the lobby program!
      </Description>
      <Response />
    </Command>

    <Command Name="REGISTER" Source="client">
      <Arguments>
        <Argument Name="username" Optional="no" Sentence="no" />
        <Argument Name="password" Optional="no" Sentence="no">
        Must be sent in encoded form (MD5 hash in base-64 form).
        </Argument>
      </Arguments>
      <Description>
      Client sends this command when trying to register a new account. Note that client mustn't already be
      logged in, or else server will deny his request. If server is running in LAN_MODE, this command will be ignored.
      </Description>
      <Response>
      Server will respond with either <clink name="REGISTRATIONDENIED"/> or <clink name="REGISTRATIONACCEPTED"/> command.
      </Response>
      <Examples>
        <Example>REGISTER Johnny Gnmk1g3mcY6OWzJuM4rlMw==</Example>
      </Examples>
    </Command>

    <Command Name="REGISTRATIONDENIED" Source="server">
      <Arguments>
        <Argument Name="reason" Optional="no" Sentence="yes" />
      </Arguments>
      <Description>
      Sent to client who has just sent <clink name="REGISTER"/> command, if registration has been refused.
      </Description>
    </Command>

    <Command Name="REGISTRATIONACCEPTED" Source="server">
      <Description>
      Sent to client who has just sent <clink name="REGISTER"/> command, if registration has been accepted.
      </Description>
    </Command>

    <Command Name="RENAMEACCOUNT" Source="client">
      <Arguments>
        <Argument Name="newUsername" Optional="no" Sentence="no" />
      </Arguments>
      <Description>
      Will rename current account which is being used by the user to newUsername. User has to be logged in for this
      to work. After server renames the account, it will disconnect him.
      </Description>
      <Response>
      No response is prescribed, although server may reply with some <clink name="SERVERMSG"/> command.
      </Response>
      <Examples>
        <Example>RENAMEACCOUNT Johnny2</Example>
      </Examples>
    </Command>

    <Command Name="CHANGEPASSWORD" Source="client">
      <Arguments>
        <Argument Name="oldPassword" Optional="no" Sentence="no" />
        <Argument Name="newPassword" Optional="no" Sentence="no" />
      </Arguments>
      <Description>
      Will change password of client's account (which he is currently using).
      </Description>
      <Response>
      No response is prescribed, although server may reply with some <clink name="SERVERMSG"/> command.
      </Response>
    </Command>

    <Command Name="LOGIN" Source="client">
      <Arguments>
        <Argument Name="username" Optional="no" Sentence="no" />
        <Argument Name="password" Optional="no" Sentence="no">
        Should be sent in encoded form (MD5 hash in base-64 form).
        Note that when server is running in lan mode, you can specify any username and password
